development:
  stripe_secret_key: 'sk_test_51HdrkvIHXlh4Q8aV5dIl68srmVqUfCvA6MsmQfz1MpS5AmBlIrbVo9anW9uvymR1GbX6obGZpJUzelYdDwEujIks00lxQnfmFq'
  stripe_publishable_key: 'pk_test_51HdrkvIHXlh4Q8aV9zjQ2QyJ3Uk9BHZHQXSLWNd9oSIW1ULY2HaZ8Gt3hZluY8kKpxO9WVkIojGgOWKkhq2d5g4Q00Asr2M9up'

production:
  stripe_secret_key: 'sk_live_aLvPhyGtUwlLSHvms3KhCdrL'
  stripe_publishable_key: 'pk_live_nbTqsm8Gg0eHGrQVRbWnjlyN'
